<?php if(!defined('ABSPATH')) die('Access denied'); 
get_header();
  get_template_part('template-parts/pages/front-page/front', 'produtos');
  get_template_part('template-parts/pages/front-page/front', 'sobre');
  get_template_part('template-parts/pages/front-page/front', 'descricao');
  get_template_part('template-parts/pages/front-page/front', 'preservacao');
  get_template_part('template-parts/pages/front-page/front', 'sustentavel');
  get_template_part('template-parts/pages/front-page/front', 'blog');
  get_template_part('template-parts/pages/front-page/front', 'contato');
  get_template_part('template-parts/pages/front-page/front', 'equipe');
  get_template_part('template-parts/pages/front-page/front', 'empresas');
get_footer();