name: Update Prod Branch and Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_prod_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or checkout prod branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/prod; then
            git checkout prod
            git merge --no-ff main -m "Merge branch 'main' into 'prod'"
          else
            git checkout -b prod
            git merge --no-ff main -m "Merge branch 'main' into 'prod'"
          fi

      - name: Remove unwanted files and directories
        run: |
          rm -rf .dev
          rm -rf .github
          rm -rf node_modules
          rm -f .gitignore
          rm -f gulpfile.js
          rm -f package-lock.json
          rm -f package.json
          rm -f .gitattributes

      - name: Commit and push changes to prod branch
        run: |
          git add .
          git commit -m "Remove unwanted files and directories"
          git push origin prod --force

      - name: Create Release from prod branch
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          release_name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          target_commitish: "prod"