name: Update Prod Branch

on:
  push:
    branches:
      - main

jobs:
  update_prod_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or checkout prod branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/prod; then
            git checkout prod
            git merge --no-ff main -m "Merge branch 'main' into 'prod'"
          else
            git checkout -b prod
            git merge --no-ff main -m "Merge branch 'main' into 'prod'"
          fi

      - name: Remove unwanted files and directories
        run: |
          rm -rf .dev
          rm -rf .github
          rm -rf node_modules
          rm -f .gitignore
          rm -f gulpfile.js
          rm -f package-lock.json
          rm -f package.json

      - name: Commit changes
        run: |
          git add .
          git commit -m "Remove unwanted files and directories"

      - name: Push to prod branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin prod --force