name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Configure Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create prod branch if it does not exist
      run: |
        git checkout prod || git checkout -b prod

    - name: Remove unwanted directories / files
      run: |
        echo "Removendo arquivos e diretórios indesejados"
        rm -rf .dev
        rm -rf node_modules
        rm -f .gitignore
        rm -f gulpfile.js
        rm -f package-lock.json
        rm -f package.json

    - name: Commit changes
      run: |
        echo "Adicionando arquivos ao commit"
        git add -A
        echo "Comitando mudanças"
        git commit -m 'Deploy para Prod'
        echo "Fazendo push para a branch prod"
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/LyonMuller/ldev-granfort.git prod --force

    - name: Remove .git directory
      run: |
        echo "Removendo diretório .git"
        rm -rf .git

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: "v1.0.${{ github.run_number }}"
        release_name: "Release v1.0.${{ github.run_number }}"
        draft: false
        prerelease: false